---
title: "Sweden Offical COVID-19 Cases"
author: "David Jackson"
date: "1/21/2021"
output: 
  html_document: 
    fig_width: 8
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
library(readxl)
library(tidyr)
library(plotly)
library(lubridate)
```

## Read Excel Sheet

```{r}
rm(list=ls())
Sweden <- readxl::read_xlsx("./Folkhalsomyndigheten_Covid19.xlsx") %>%
  rename(Date = Statistikdatum) %>%
  rename(Cases = Totalt_antal_fall)

Sweden$Date <- as.Date(Sweden$Date)
```

```{r}
daily_cases <- Sweden %>% group_by(Date) %>%
        summarise(Total = sum(Cases)) 
```

```{r}
plot1 <-daily_cases %>% filter(Date >="2020-09-01") %>%
ggplot() + geom_col(aes(x=Date,y=Total)) + 
  labs(total="Sweden Cases by Day") +
scale_y_continuous(labels=comma)

ggplotly(plot1)
```

## Total Cases by Week (Sunday - Saturday)

```{r}
weekly_cases <- Sweden %>% group_by(Weekly = floor_date(Date, "week")) %>%
        summarise(Total = sum(Cases)) 
```

```{r}
plot2 <- ggplot(weekly_cases) + geom_col(aes(x=Weekly,y=Total)) +
  scale_y_continuous(labels=comma) +
  labs(title = "Sweden Weekly Cases",y="Total Cases")
ggplotly(plot2)
```

## Plot Sweden Weekly Cases from Our World In Data (JHU)

```{r}
library(RSQLite)
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
df <- dbGetQuery(db,"select * from JHU where location = 'Sweden' ")
df$date <- as.Date(df$date)
```
```{r}
ggplot(df) + geom_col(aes(x=date,y=weekly_cases)) +
  scale_y_continuous(labels=comma) +
  labs(title="Sweden Weely Cases",subtitle = "(Source: Our World In Data)")
```
```{r}
ggplot(df) + geom_line(aes(x=date,y=weekly_cases,col="OWID")) +
  scale_y_continuous(labels=comma) + 
  geom_line(data=weekly_cases,aes(x=Weekly,y=Total,col="Sweden"))
```

