---
title: "Sweden Numers Part 4"
author: "David Jackson"
date: "1/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
library(dplyr)
library(forecast)
```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
EU <- dbGetQuery(db,"select * from OWID where location='Sweden'")
df <- dbGetQuery(db,"select * from JHU ")

df <- subset(df,location =="Sweden"  )

df$date <- as.Date(df$date)
EU$date <- as.Date(EU$date)
df <- df[order(df$date),]
EU <- EU[order(EU$date),]
df$CMA <- ma(df$new_cases,7,centre=TRUE)
df$DMA <- ma(df$new_deaths,7,centre=TRUE)
dbDisconnect(db)
```
##

```{r}

plot1 <-df %>% ggplot() + geom_col(aes(x=date,y=new_cases))

df %>% ggplot() + geom_line(aes(x=date,y=CMA))
```
```{r}
df$MAD <- ma(df$new_deaths,7)
plot2 <- df %>% ggplot() + geom_col(aes(x=date,y=new_deaths))
ggplotly(plot1)
ggplotly(plot2)

df %>% ggplot() + geom_line(aes(x=date,y=DMA))
```
```{r}
short <- df %>% filter(date >="2020-04-01" & date <="2020-10-01")
plot3 <- short %>% ggplot() + geom_col(aes(x=date,y=new_cases))

short %>% ggplot() + geom_line(aes(x=date,y=CMA))
ggplotly(plot3)

plot4 <-short %>% ggplot() + geom_col(aes(x=date,y=new_deaths))

short %>% ggplot() + geom_line(aes(x=date,y=MAD))

ggplotly(plot4)
```


