---
title: 'SWEDEN: COVID-19 Analysis'
author: "David Jackson"
date: "`r Sys.time()`"
output: 
  html_document: 
    fig_width: 8
    fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
library(dplyr)
# library(forecast)
library(pracma)
library(timetk)
# theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
theme_set(theme_light())

```
```{r}
rm(list=ls())
# source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/OURWORLD.sqlite3")
df <- dbGetQuery(db,"select * from OWID")
df <- subset(df,location =="Sweden"  )
df$date <- as.Date(df$date)
df <- df[order(df$date),]
df <- df %>% filter(date >= Sys.Date() -365)
### Replace NA with mean new_deaths
df$new_deaths[which(is.na(df$new_deaths))] <- mean(df$new_deaths,na.rm = TRUE)
df$new_deaths<- ifelse(df$new_deaths <0,mean(df$new_deaths,na.rm = TRUE),df$new_deaths)
df$CMA <- movavg(df$new_cases,14,type = "e")
df$DMA <- movavg(df$new_deaths,14,type = "e")
# dbDisconnect(db)
```

#### Example of : Daily data is compiled Tuesdays to Fridays 
* https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/

```{r}
df$Year <- lubridate::year(df$date)
df$Year <- as.factor(df$Year)
ggplot(df) + geom_col(aes(x=Year,y=new_cases)) +
  labs(title = "Covid-19 Cases By Year") +
  scale_y_continuous(labels = comma)

ggplot(df) + geom_col(aes(x=Year,y=new_deaths)) +
  labs(title = "Covid-19 Deaths By Year") +
  scale_y_continuous(labels = comma)
```
```{r}
# df$Year <- as.factor(df$Year)
# ggplot(df) + geom_col(aes(x=Year,y=new_cases)) +
#   labs(title = "Covid-19 Cases By Year") +
#   scale_y_continuous(labels = comma)
# 
# ggplot(df) + geom_col(aes(x=Year,y=new_deaths)) +
#   labs(title = "Covid-19 Deaths By Year") +
#   scale_y_continuous(labels = comma)
```





```{r}
p1 <- df  %>%
  ggplot() + geom_col(aes(x=date,y=new_cases,col="Daily Cases")) +
  labs(title="Cases: Plot of Tuesday - Friday Data.") +ylim(0,10000) +
  geom_smooth(aes(x=date,y=new_cases),span=0.1)

p2 <- df %>% filter(date >="2020-01-01" ) %>%
  ggplot() + geom_col(aes(x=date,y=CMA)) +
  labs(title="Cases : 14 Day Moving Average")

p3 <- df %>% filter(date >="2020-01-01" ) %>%
  ggplot() + geom_col(aes(x=date,y=new_deaths)) +
  labs(title="Deaths: Plot of Tuesday - Friday Data. ") +ylim(0,150) +
  geom_smooth(aes(x=date,y=new_deaths,col="Loess"),span=0.1) +
  geom_smooth(aes(x=date,y=new_deaths,col="lm"),method = "lm")
p4 <- df %>% filter(date >="2020-01-01") %>%
  ggplot() + geom_col(aes(x=date,y=DMA)) +
  labs(title="Deaths: 14 Day Moving Average")
ggplotly(p1)
ggplotly(p2)
ggplotly(p3)
ggplotly(p4)
```

#### Non-Moving Average By Week and By Month

```{r}
df$Monthly <- as.Date(cut(df$date,
  breaks = "month"))
df$Weekly <- as.Date(cut(df$date,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_new_cases <- aggregate(new_cases~Weekly,df,FUN=sum)
Weekly_new_deaths <- aggregate(new_deaths~Weekly,df,FUN=sum)

```
```{r}

df %>% group_by(date) %>%
  summarise_by_time(date,.by = "week",Cases =sum(new_cases)) %>%
  ggplot() + geom_col(aes(x=date,y=Cases,col="Cases"),lwd=2) +
  labs(title = "Sweden Covid-19 Cases by Week")

df %>% group_by(date) %>%
  summarise_by_time(date,.by = "week",Deaths =sum(new_deaths)) %>%
  ggplot() + geom_col(aes(x=date,y=Deaths,col="Deaths"),lwd=2) +
  labs(title = "Sweden Covid-19 Deaths by Week")
``` 

#### Monthly new_cases and new_deaths

```{r}

Monthly_new_cases <- aggregate(new_cases~Monthly,df,FUN=sum)
Monthly_new_deaths <- aggregate(new_deaths~Monthly,df,FUN=sum)


```
```{r}
ggplot(Monthly_new_cases) + geom_col(aes(x=Monthly,y=new_cases)) +
  labs(title="Monthly Cases") +
  scale_y_continuous(labels = scales::comma)

ggplot(Monthly_new_deaths) + geom_col(aes(x=Monthly,y=new_deaths)) +
  labs(title="Monthly Deaths") +
  scale_y_continuous(labels = scales::comma)
```

